name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for upstream changes
        run: |
          git remote add upstream https://github.com/astrix-network/astrix-node.git
          git fetch upstream

          UPSTREAM_LATEST_COMMIT=$(git rev-parse upstream/main)

          if [ -f upstream-latest.txt ]; then
            LAST_SAVED_COMMIT=$(cat upstream-latest.txt)
          else
            LAST_SAVED_COMMIT=""
          fi


          if [ "$UPSTREAM_LATEST_COMMIT" = "$LAST_SAVED_COMMIT" ]; then
            echo "No changes in upstream. Skipping build."
            exit 0
          else
            echo "Changes detected in upstream. Proceeding with build."
          fi

          echo $UPSTREAM_LATEST_COMMIT > upstream-latest.txt

      - name: Commit and push upstream-latest.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add upstream-latest.txt
          git commit -m "Update upstream latest commit hash"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "casraw/allgemein"
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push latest image
        uses: docker/build-push-action@v6
        with:
          tags: "casraw/astrix-node-docker:latest"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Build and push commit-specific image
        uses: docker/build-push-action@v6
        with:
          tags: "casraw/astrix-node-docker:${{ github.sha }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Enable Docker Content Trust (DCT)
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker pull casraw/astrix-node-docker:latest

      - name: Install Syft for SBoM generation
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBoM for the Docker image
        run: syft casraw/astrix-node-docker:latest -o json > sbom.json

      - name: Upload SBoM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: casraw/astrix-node-docker
          readme-filepath: ./README.md

      - name: Docker Scout Analysis
        uses: docker/scout-action@v1
        with:
          image: casraw/astrix-node-docker:latest
