name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "casraw/allgemein"
          install: true
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "casraw/astrix-node-docker:latest"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "casraw/astrix-node-docker:${{ github.sha }}"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
      - name: Enable Docker Content Trust (DCT)
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker pull casraw/astrix-node-docker:latest
      - name: Install Syft for SBoM generation
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBoM for the Docker image
        run: syft casraw/astrix-node-docker:latest -o json > sbom.json
      - name: Upload SBoM artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: sbom.json
      - name: Update Docker Hub description
      - name: Docker Scout Analysis
        uses: docker/scout-action@v1
        with:
          image: casraw/astrix-node-docker:latest
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: casraw/astrix-node-docker
          readme-filepath: ./README.md